- name: Install Python tooling
  homebrew:
    name:
      - python@3.12
      - pyenv
      - poetry
      - pipx
    state: present

- name: Install Python developer tools
  shell: |
    pipx install jupyterlab
    pipx install black
    pipx install ruff
    pipx install mypy
  args:
    creates: ~/.local/bin/jupyter-lab

