- name: Check if Homebrew exists
  stat:
    path: /opt/homebrew/bin/brew
  register: brew_check

- name: Install Homebrew
  shell: |
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  when: not brew_check.stat.exists

- name: Add Homebrew to PATH
  lineinfile:
    path: ~/.zprofile
    line: 'eval "$(/opt/homebrew/bin/brew shellenv)"'
    create: yes

